FROM hashicorp/terraform:1.11.2 AS base
ARG DOCKER_PROJECT_DIR
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV PROJECT_DIR=$DOCKER_PROJECT_DIR
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

FROM base AS builder
RUN apk add --update bash git findutils make openrc tree
WORKDIR $PROJECT_DIR
COPY . ./
RUN make test package
ENTRYPOINT tail -f /dev/null
