name: &service_name gateway-service
port: &port 80
vpc: master
subnet_group: main
cluster: main
config:
  default:
    desired_count: 1
    health_check:
      protocol: 'HTTP'
      port: *port
      path: '/'
      healthy_threshold: 4
      unhealthy_threshold: 3
      interval: 100
      timeout: 10
      success_codes: '200-299'
    task_definition:
      name: *service_name
      image: nginx
      cpu: 512
      memory: 1024
      portMappings:
        - containerPort: *port
          hostPort: *port
    variables:
      SERVICE_NAME: *service_name
      PORT: *port
      AWS_S3_BUCKET_FOR_DOCUMENTS: cloudgrove.${env}.archives
      AWS_S3_BUCKET_FOR_PUBLIC_CONTENT: &pc_bucket cloudgrove.${env}.public-assets
      POSTGRES_HOST: gateway-service-postgres.master
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: &default_pg_pass kms_AQICAHjYdH1UxKqA9GWR7DagdD0uKERhRQZZkDpVM4wEn2l/gQHRh+zGk2Gg+aF8pXibLn3IAAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMffBhCZjMsGx3WJIgAgEQgCP9tPye94Rh9itGgWxNLcuVovdu6mLrrJIBsTDpkhBK633xiA==
      POSTGRES_DATABASE: main
    resources:
      efs:
        - /var/gateway-service
        - /var/shared
      rds:
        postgres:
          engine: postgres
          engine_version: 18.1
          password: *default_pg_pass
      sqs:
        low:
          delay_seconds: 3
        medium:
        high:
          fifo_queue: true
      s3:
        read_write:
          - cloudgrove.${env}.archives/gateway-service
          - cloudgrove.${env}.archives/shared
        read_only:
          - *pc_bucket
  beta:
    desired_count: 2
    task_definition:
      image: nginx
  prod:
    desired_count: 0
    task_definition:
      image: nginx
